import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Main.module.css'
import { useState, useEffect } from 'react'
import { Meeting } from './Meeting'
import { Schedule } from './Schedule'
import { Home } from './Home'
import Dropdown from 'react-bootstrap/Dropdown';
import Badge from 'react-bootstrap/Badge';
import CloseButton from 'react-bootstrap/CloseButton';

export default function Main() {
    const [MenuActive, SetMenu] = useState("");
    const [date, SetDate] = useState(new Date());

    let MainView;

    if (MenuActive == 'Home') {
        MainView = <Home setMenu={SetMenu} />
    } else if (MenuActive == 'Meeting') {
        MainView = <Meeting />
    } else if (MenuActive == 'Schedule') {
        MainView = <Schedule />
    } else {
        MainView = MenuActive;
    }

    useEffect(() => {
        SetMenu("Home")

        const interval = setInterval(() => SetDate(new Date()), 1000);

        return () => {
            clearInterval(interval);
        }
      }, [])

    const MenuNameEn = ['Home', 'Meeting', 'Schedule'];
    const MenuIcon = ['bi bi-house-door', 'bi bi-briefcase', 'bi bi-calendar-check'];

    const MenuRendering = () => {
        const result = [];
        for(let i = 0; i < MenuNameEn.length; i++) {
            result.push(
              <li key={i} className={`${MenuActive == MenuNameEn[i] ? styles.active : styles.disabled} ${styles.menu_li}`} id='menu_li' onClick={() => SetMenu(MenuNameEn[i])}>
                <i className={MenuIcon[i]}></i>
              </li>
            )
        }
        return result;
    }


    return (
        <div className={styles.wrap}>
            <Head>
                <title>실시간 채팅</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.sidebar}>
                <div className={styles.sidebar_header}>
                    <Image src="/logo.svg" width={50} height={50} />
                </div>
                <div className={styles.menu}>
                    <ul className={styles.menu_ul}>
                        <div>
                            {
                                MenuRendering()
                             }
                        </div>
                        <div>
                            <li className={`${styles.menu_li}`} id='menu_li'>
                                <i className="bi bi-box-arrow-left"></i>
                            </li>
                        </div>
                    </ul>
                </div>
            </div>
            <div className={styles.contents}>
                <header className={styles.contents_header}>
                    <div className={styles.contents_header_right_side}>
                        <div className={styles.Search}>
                            <i className="bi bi-search"></i>
                            <input type="text" placeholder='Search anything' autoComplete='off'></input>
                        </div>
                        <Dropdown>
                            <Dropdown.Toggle as='span' bsPrefix='toggle' className='d-flex align-items-start'>
                                <i className="bi bi-bell" style={{cursor: 'pointer'}}></i>
                                <Badge bg="danger" pill>2</Badge>
                            </Dropdown.Toggle>
                            <Dropdown.Menu id='dropdown-menu'>
                                <Dropdown.Item>
                                    <div className="d-flex justify-content-between align-items-center">
                                        <div className="ms-2 me-auto small">
                                            <div className="fw-bold">회의 알림</div>
                                            초대
                                        </div>
                                    </div>
                                </Dropdown.Item>
                                <Dropdown.Item>
                                    <div className="d-flex justify-content-between align-items-center">
                                        <div className="ms-2 me-auto small">
                                            <div className="fw-bold">회의 알림</div>
                                            초대
                                        </div>
                                    </div>
                                </Dropdown.Item>
                            </Dropdown.Menu>
                        </Dropdown>
                    </div>
                </header>
                {MainView}
            </div>
        </div>
    )
}
